services:
  - type: web
    name: play-hub
    runtime: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
